const allProducts = [
  {
    id: 1,
    prodImg: "/images/customImg/product-1.webp",
    prodName: "Ample Basket",
    vendName: "Digital Dezire",
    sku: "GL3946",
    stock: "In Stock",
    price: "700.00",
    old_price: "₹1500.00",
    CategType: "HomeEssentials",
    Category: "Home Essentials",
    Date: "2023/10/15 at 17.44",
    star: "fa-regular",
  },

  {
    id: 2,
    prodImg: "/images/customImg/product-2.webp",
    prodName: "1 Comb",
    vendName: "Digital Dezire",

    sku: "GL3946",
    stock: "In Stock",
    price: "500.00",
    old_price: "₹900.00",
    CategType: "HomeEssentials",
    Category: "Home Essentials",
    Date: "2023/10/15 at 17.44",
    star: "fa-regular",
  },

  {
    id: 3,
    prodImg: "/images/customImg/product-3.webp",
    prodName: "Copper Mug (Moscow Male)",
    vendName: "Brand Orbiter",
    sku: "GL3946",
    stock: "Out of Stock",
    price: "1399.00",
    old_price: "2000.00",
    CategType: "HomeEssentials",
    Category: "Home Essentials",
    Date: "2023/10/15 at 17.44",
    star: "fa-regular",
  },

  {
    id: 4,
    prodImg: "/images/customImg/product-4.png",
    prodName: "Bamboo Lamp Jaali",
    vendName: "Brand Orbiter",
    sku: "GL3946",
    stock: "In Stock",
    price: "1200.00",
    old_price: "₹1800.00",
    CategType: "Furniture",
    Category: "Furniture",
    Date: "2023/10/15 at 17.44",
    star: "fa-regular",
  },

  {
    id: 5,
    prodImg: "/images/customImg/product-5.png",
    prodName: "Laundry Basket",
    vendName: "The Green Samaan Shop",
    sku: "GL3946",
    stock: "In Stock",
    price: "2200.00",
    old_price: "₹3000.00",
    CategType: "Furniture",
    Category: "Furniture",
    Date: "2023/10/15 at 17.44",
    star: "fa-regular",
  },

  {
    id: 6,
    prodImg: "/images/customImg/product-6.webp",
    prodName: "Bamboo ToothBrush",
    vendName: "The Green Samaan Shop",
    sku: "GL3946",
    stock: "Out of Stock",
    price: "350.00",
    old_price: "₹550.00",
    CategType: "bathroom",
    Category: "bathroom Essentials",
    Date: "2023/10/15 at 17.44",
    star: "fa-regular",
  },

  {
    id: 7,
    prodImg: "/images/customImg/product-7.jpg",
    prodName: "Magazine Basket",
    vendName: "The Green Samaan Shop",
    sku: "GL3946",
    stock: "In Stock",
    price: "900.00",
    old_price: "₹1499.00",
    CategType: "bathroom",
    Category: "bathroom Essentials",
    Date: "2023/10/15 at 17.44",
    star: "fa-regular",
  },

  {
    id: 8,
    prodImg: "/images/customImg/product-8.png",
    prodName: "Chocolate Cream Sandwich Cookie",
    vendName: "Brand Orbiter",
    sku: "GL3946",
    stock: "In Stock",
    price: "350.00",
    old_price: "550.00",
    CategType: "Food",
    Category: "Food & Nutrition",
    Date: "2023/10/15 at 17.44",
    star: "fa-regular",
  },

  {
    id: 9,
    prodImg: "/images/customImg/product-9.png",
    prodName: "Kesar Nan Khattai",
    vendName: "Brand Orbiter",
    sku: "GL3946",
    stock: "Out of Stock",
    price: "400.00",
    old_price: "599.00",
    CategType: "Food",
    Category: "Food & Nutrition",
    Date: "2023/10/15 at 17.44",
    star: "fa-regular",
  },

  {
    id: 10,
    prodImg: "/images/customImg/product-10.png",
    prodName: "Sugar-Free Zeera cookies",
    vendName: "Digital Dezire",

    sku: "GL3946",
    stock: "In Stock",
    price: "260.00",
    old_price: "699.00",
    CategType: "Food",
    Category: "Food & Nutrition",
    Date: "2023/10/15 at 17.44",
    star: "fa-regular",
  },
];

export default allProducts;
