const alluserData = [
    {
      id: 1,
      profImg: "./images/customImg/c-1.jpg",
      userId: "23456778",
      userName: "Richard Parker",
      Mobile: "4587599832",
      email: "parker011@gmail.com",
      userType: "User",
      userStatus : "Active",
      categoryStatus : "Active",
      categoryType : "user",
      City: "Mumbai",
      Zip: "110008",
    },

 

    {
      id: 2,
      profImg: "./images/customImg/c-2.jpg",
      userId: "23456778",
      userName: "Richard Parker",
      Mobile: "4587599832",
      email: "parker011@gmail.com",
      userType: "User",
      userStatus : "Active",
      categoryStatus : "Active",
      categoryType : "user",
      City: "Mumbai",
      Zip: "110008",
    },

    {
      id: 3,
      profImg: "./images/customImg/c-3.jpg",
      userId: "23456778",
      userName: "Richard Parker",
      Mobile: "4587599832",
      email: "parker011@gmail.com",
      userType: "Vendor",
      userStatus : "Active",
      categoryStatus : "Active",
      categoryType : "Vendor",
      City: "Mumbai",
      Zip: "110008",
    },

    {
      id: 4,
      profImg: "./images/customImg/c-4.jpg",
      userId: "23456778",
      userName: "Richard Parker",
      Mobile: "4587599832",
      email: "parker011@gmail.com",
      userType: "Waste Collector",
      userStatus : "Banned",
      categoryStatus : "Banned",
      categoryType : "WasteCollector",
      City: "Mumbai",
      Zip: "110008",
    },
    {
      id: 5,
      profImg: "./images/customImg/c-1.jpg",
      userId: "23456778",
      userName: "Richard Parker",
      Mobile: "4587599832",
      email: "parker011@gmail.com",
      userType: "Waste Collector",
      userStatus : "Unverified",
      categoryStatus : "Unverified",
      categoryType : "WasteCollector",
      City: "Mumbai",
      Zip: "110008",
    },
    {
      id: 6,
      profImg: "./images/customImg/c-2.jpg",
      userId: "23456778",
      userName: "Richard Parker",
      Mobile: "4587599832",
      email: "parker011@gmail.com",
      userType: "Staff (Support Team)",
      userStatus : "Active",
      categoryStatus : "Active",
      categoryType : "SupportTeam",
      City: "Mumbai",
      Zip: "110008",
    },
    {
      id: 7,
      profImg: "./images/customImg/team-2.jpg",
      userId: "23456778",
      userName: "Richard Parker",
      Mobile: "4587599832",
      email: "parker011@gmail.com",
      userType: "Staff (Sales Team)",
      userStatus : "Banned",
      categoryStatus : "Banned",
      categoryType : "SalesTeam",
      City: "Mumbai",
      Zip: "110008",
    },
    {
      id: 8,
      profImg: "./images/customImg/team-4.jpg",
      userId: "23456778",
      userName: "Richard Parker",
      Mobile: "4587599832",
      email: "parker011@gmail.com",
      userType: "Staff (Sales Team)",
      userStatus : "Banned",
      categoryStatus : "Banned",
      categoryType : "SalesTeam",
      City: "Mumbai",
      Zip: "110008",
    },
    {
      id: 9,
      profImg: "./images/customImg/c-4.jpg",
      userId: "23456778",
      userName: "Richard Parker",
      Mobile: "4587599832",
      email: "parker011@gmail.com",
      userType: "Staff (Sales Team)",
      userStatus : "Active",
      categoryStatus : "Active",
      categoryType : "SalesTeam",
      City: "Mumbai",
      Zip: "110008",
    },
    {
      id: 10,
      profImg: "./images/customImg/c-3.jpg",
      userId: "23456778",
      userName: "Richard Parker",
      Mobile: "4587599832",
      email: "parker011@gmail.com",
      userType: "Staff (Support Team)",
      userStatus : "Active",
      categoryStatus : "Active",
      categoryType : "SupportTeam",
      City: "Mumbai",
      Zip: "110008",
    },
    {
      id: 11,
      profImg: "./images/customImg/team-2.jpg",
      userId: "23456778",
      userName: "Richard Parker",
      Mobile: "4587599832",
      email: "parker011@gmail.com",
      userType: "Staff (Manager)",
      userStatus : "Active",
      categoryStatus : "Active",
      categoryType : "Manager",
      City: "Mumbai",
      Zip: "110008",
    },
    {
      id: 12,
      profImg: "./images/customImg/team-3.jpg",
      userId: "23456778",
      userName: "Richard Parker",
      Mobile: "4587599832",
      email: "parker011@gmail.com",
      userType: "Staff (Manager)",
      userStatus : "Banned",
      categoryStatus : "Banned",
      categoryType : "Manager",
      City: "Mumbai",
      Zip: "110008",
    },
    {
        id: 13,
        profImg: "./images/customImg/c-1.jpg",
        userId: "23456778",
        userName: "Richard Parker",
        Mobile: "4587599832",
        email: "parker011@gmail.com",
        userType: "Frenchies",
        userStatus : "Unverified",
        categoryStatus : "Unverified",
        categoryType : "Frenchies",
        City: "Mumbai",
        Zip: "110008",
      },
      {
        id: 14,
        profImg: "./images/customImg/c-1.jpg",
        userId: "23456778",
        userName: "Richard Parker",
        Mobile: "4587599832",
        email: "parker011@gmail.com",
        userType: "Frenchies",
        userStatus : "Active",
        categoryStatus : "Active",
        categoryType : "Frenchies",
        City: "Mumbai",
        Zip: "110008",
      },
      {
        id: 15,
        profImg: "./images/customImg/c-1.jpg",
        userId: "23456778",
        userName: "Richard Parker",
        Mobile: "4587599832",
        email: "parker011@gmail.com",
        userType: "Vendor",
        userStatus : "Banned",
        categoryStatus : "Banned",
        categoryType : "Vendor",
        City: "Mumbai",
        Zip: "110008",
      },

      {
        id: 16,
        profImg: "./images/customImg/c-1.jpg",
        userId: "23456778",
        userName: "Richard Parker",
        Mobile: "4587599832",
        email: "parker011@gmail.com",
        userType: "Staff (Sales Team)",
        userStatus : "Unverified",
        categoryStatus : "Unverified",
        categoryType : "SalesTeam",
        City: "Mumbai",
        Zip: "110008",
      },

      {
        id: 17,
        profImg: "./images/customImg/c-1.jpg",
        userId: "23456778",
        userName: "Richard Parker",
        Mobile: "4587599832",
        email: "parker011@gmail.com",
        userType: "Staff (Support Team)",
        userStatus : "Active",
        categoryStatus : "Active",
        categoryType : "Support Team",
        City: "Mumbai",
        Zip: "110008",
      },

      {
        id: 18,
        profImg: "./images/customImg/c-1.jpg",
        userId: "23456778",
        userName: "Richard Parker",
        Mobile: "4587599832",
        email: "parker011@gmail.com",
        userType: "User",
        userStatus : "Unverified",
        categoryStatus : "Unverified",
        categoryType : "User",
        City: "Mumbai",
        Zip: "110008",
      },

      {
        id: 19,
        profImg: "./images/customImg/c-1.jpg",
        userId: "23456778",
        userName: "Richard Parker",
        Mobile: "4587599832",
        email: "parker011@gmail.com",
        userType: "User",
        userStatus : "Banned",
        categoryStatus : "Banned",
        categoryType : "User",
        City: "Mumbai",
        Zip: "110008",
      },

      {
        id: 20,
        profImg: "./images/customImg/c-1.jpg",
        userId: "23456778",
        userName: "Richard Parker",
        Mobile: "4587599832",
        email: "parker011@gmail.com",
        userType: "Vendor",
        userStatus : "Unverified",
        categoryStatus : "Unverified",
        categoryType : "Vendor",
        City: "Mumbai",
        Zip: "110008",
      },
  ];

  export default alluserData 