const frienchiesData = [
  {
    id: 1,
    profImg: "/images/customImg/c-1.jpg",
    userId: "23456778",
    userName: "Richard Parker",
    companyName: "Digital Dezire",
    workArea: "Laxmi Nagar",
    Mobile: "4587599832",
    email: "parker011@gmail.com",
    userStatus: "active",
    categoryStatus: "active",
    substype: "Monthly",
    City: "Delhi",
    Zip: "110008",
    action: "approve",
  },

  {
    id: 2,
    profImg: "/images/customImg/c-1.jpg",
    userId: "23456778",
    userName: "Tobey",
    companyName: "Brand Orbiter",
    workArea: "Gandhi Nagar",
    Mobile: "4587599832",
    email: "parker011@gmail.com",
    userStatus: "active",
    categoryStatus: "active",
    substype: "Monthly",
    City: "Mumbai",
    Zip: "110008",
    action: "disapprove",
  },

  {
    id: 3,
    profImg: "/images/customImg/c-1.jpg",
    userId: "23456778",
    userName: "Andrew Garfield",
    companyName: "ClimStripe",
    workArea: "Gandhi Nagar",
    Mobile: "4587599832",
    email: "parker011@gmail.com",
    userStatus: "Banned",
    categoryStatus: "banned",
    substype: "Monthly",
    City: "Mumbai",
    Zip: "110008",
    action: "approve",
  },

  {
    id: 4,
    profImg: "/images/customImg/c-1.jpg",
    userId: "23456778",
    userName: "Richard Parker",
    companyName: "Digital Dezire",
    workArea: "Laxmi Nagar",
    Mobile: "4587599832",
    email: "parker011@gmail.com",
    userStatus: "active",
    categoryStatus: "active",
    substype: "Monthly",
    City: "Delhi",
    Zip: "110008",
    action: "disapprove",
  },

  {
    id: 5,
    profImg: "/images/customImg/c-1.jpg",
    userId: "23456778",
    userName: "Tobey",
    companyName: "Brand Orbiter",
    workArea: "Gandhi Nagar",
    Mobile: "4587599832",
    email: "parker011@gmail.com",
    userStatus: "active",
    categoryStatus: "active",
    substype: "Quaterly",
    City: "Mumbai",
    Zip: "110008",
    action: "approve",
  },

  {
    id: 6,
    profImg: "/images/customImg/c-1.jpg",
    userId: "23456778",
    userName: "Andrew Garfield",
    companyName: "ClimStripe",
    workArea: "Gandhi Nagar",
    Mobile: "4587599832",
    email: "parker011@gmail.com",
    userStatus: "Banned",
    categoryStatus: "banned",
    substype: "Quaterly",

    City: "Mumbai",
    Zip: "110008",
    action: "disapprove",
  },
];

export default frienchiesData;
